# Apply only with --context=docker-desktop.
apiVersion: v1
kind: Service
metadata:
  name: messaging-backend
  namespace: messaging
spec:
  type: LoadBalancer
  selector:
    app: messaging-backend
  ports:
    - name: http
      port: 8001
      targetPort: http
