package com.messaging.company.enums;

public enum CompanyPermission {
  COMPANY_VIEW,
  COMPANY_UPDATE,
  MEMBER_INVITE,
  MEMBER_REMOVE,
  MEMBER_ROLE_UPDATE,
  BILLING_VIEW,
  BILLING_MANAGE,
  BROADCAST_CREATE,
  BROADCAST_APPROVE,
  TEMPLATE_CREATE,
  TEMPLATE_APPROVE,
  MESSAGE_VIEW,
  MESSAGE_SEND,
  ADS_VIEW,
  ADS_MANAGE,
  SETTINGS_VIEW,
  SETTINGS_MANAGE,
  MEDIA_UPLOAD
}
