CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(320) NOT NULL CONSTRAINT uk_user_email UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(30),
    status VARCHAR(30) NOT NULL,
    email_verified BOOLEAN NOT NULL,
    phone_verified BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_user_status ON users(status);

CREATE TABLE roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL CONSTRAINT uk_role_name UNIQUE,
    description VARCHAR(255), active BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE platform_roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL CONSTRAINT uk_platform_role_name UNIQUE,
    description VARCHAR(255), active BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL, display_name VARCHAR(150), status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_company_status ON companies(status);
CREATE TABLE company_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id),
    user_id BIGINT NOT NULL REFERENCES users(id), role_id BIGINT NOT NULL REFERENCES roles(id),
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_company_membership_user_company UNIQUE(company_id, user_id)
);
CREATE INDEX idx_membership_user_id ON company_memberships(user_id);
CREATE INDEX idx_membership_company_id ON company_memberships(company_id);
CREATE INDEX idx_membership_company_status ON company_memberships(company_id, status);
CREATE TABLE company_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL UNIQUE REFERENCES companies(id),
    legal_name VARCHAR(200) NOT NULL, website VARCHAR(255), business_email VARCHAR(150),
    business_phone VARCHAR(50), industry VARCHAR(100), registration_number VARCHAR(100), tax_id VARCHAR(100)
);
CREATE TABLE company_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id),
    address_line_1 VARCHAR(255) NOT NULL, address_line_2 VARCHAR(255), city VARCHAR(100) NOT NULL,
    state VARCHAR(100), postal_code VARCHAR(30), country VARCHAR(100) NOT NULL
);
CREATE INDEX idx_company_address_company_id ON company_addresses(company_id);
CREATE TABLE company_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL UNIQUE REFERENCES companies(id),
    verification_status VARCHAR(30) NOT NULL, risk_level VARCHAR(30) NOT NULL,
    email_verified BOOLEAN NOT NULL, phone_verified BOOLEAN NOT NULL, website_verified BOOLEAN NOT NULL,
    reviewed_at TIMESTAMP WITH TIME ZONE, rejection_reason VARCHAR(1000)
);
CREATE INDEX idx_company_verification_status ON company_verifications(verification_status);
CREATE INDEX idx_company_verification_risk_level ON company_verifications(risk_level);
CREATE TABLE user_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id), platform VARCHAR(20) NOT NULL,
    refresh_token VARCHAR(64) NOT NULL, device_id VARCHAR(255), device_name VARCHAR(255),
    ip_address VARCHAR(64), user_agent VARCHAR(1000), active BOOLEAN NOT NULL,
    last_active_at TIMESTAMP WITH TIME ZONE, expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL, updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_user_platform UNIQUE(user_id, platform)
);
CREATE INDEX idx_session_user_id ON user_sessions(user_id);
CREATE INDEX idx_session_refresh_token ON user_sessions(refresh_token);
