CREATE TABLE subscription_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL CONSTRAINT uk_subscription_plan_code UNIQUE,
    account_type VARCHAR(30) NOT NULL,
    name VARCHAR(100) NOT NULL,
    monthly_price NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE subscription_plan_limits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL REFERENCES subscription_plans(id) ON DELETE CASCADE,
    feature_key VARCHAR(100) NOT NULL,
    limit_value NUMERIC(12, 2) NOT NULL,
    unit VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_subscription_plan_limit UNIQUE(plan_id, feature_key)
);

CREATE TABLE subscription_channel_pricing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id BIGINT NOT NULL REFERENCES subscription_plans(id) ON DELETE CASCADE,
    channel VARCHAR(30) NOT NULL,
    message_type VARCHAR(30) NOT NULL,
    price_per_segment NUMERIC(12, 4) NOT NULL,
    free_daily_segments INTEGER NOT NULL DEFAULT 0,
    currency VARCHAR(3) NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_subscription_channel_pricing UNIQUE(plan_id, channel, message_type)
);

CREATE TABLE company_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id),
    plan_id BIGINT NOT NULL REFERENCES subscription_plans(id),
    status VARCHAR(30) NOT NULL,
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at TIMESTAMP WITH TIME ZONE,
    renews_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_company_subscription_company UNIQUE(company_id)
);
CREATE INDEX idx_company_subscription_status ON company_subscriptions(status);

CREATE TABLE company_usage_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id),
    usage_date DATE NOT NULL,
    feature_key VARCHAR(100) NOT NULL,
    used_count NUMERIC(14, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_company_usage_daily UNIQUE(company_id, usage_date, feature_key)
);

CREATE TABLE message_usage_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id),
    channel VARCHAR(30) NOT NULL,
    message_type VARCHAR(30) NOT NULL,
    recipient_count INTEGER NOT NULL,
    segment_count INTEGER NOT NULL,
    billable_segment_count INTEGER NOT NULL,
    unit_price NUMERIC(12, 4) NOT NULL,
    total_amount NUMERIC(14, 4) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_message_usage_company_created ON message_usage_events(company_id, created_at);

CREATE TABLE company_whatsapp_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id),
    provider VARCHAR(50) NOT NULL,
    phone_number_id VARCHAR(150),
    display_phone VARCHAR(50),
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_company_whatsapp_accounts_company ON company_whatsapp_accounts(company_id);

CREATE TABLE company_sms_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id),
    provider VARCHAR(50) NOT NULL,
    sender_id VARCHAR(100),
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_company_sms_accounts_company ON company_sms_accounts(company_id);

CREATE TABLE company_email_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id),
    provider VARCHAR(50) NOT NULL,
    from_email VARCHAR(150),
    from_name VARCHAR(150),
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_company_email_accounts_company ON company_email_accounts(company_id);

CREATE TABLE company_ad_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id),
    provider VARCHAR(50) NOT NULL,
    external_account_id VARCHAR(150),
    display_name VARCHAR(150),
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_company_ad_accounts_company ON company_ad_accounts(company_id);

CREATE TABLE message_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id),
    channel VARCHAR(30) NOT NULL,
    name VARCHAR(150) NOT NULL,
    template_type VARCHAR(30) NOT NULL,
    status VARCHAR(30) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_message_templates_company_channel ON message_templates(company_id, channel);

INSERT INTO subscription_plans(code, account_type, name, monthly_price, currency, active, created_at, updated_at)
VALUES
    ('FREE_INDIVIDUAL', 'INDIVIDUAL', 'Free Individual', 0.00, 'INR', true, now(), now()),
    ('FREE_ORGANIZATION', 'ORGANIZATION', 'Free Organization', 0.00, 'INR', true, now(), now())
ON CONFLICT (code) DO NOTHING;

INSERT INTO subscription_plan_limits(plan_id, feature_key, limit_value, unit, created_at, updated_at)
SELECT p.id, limits.feature_key, limits.limit_value, limits.unit, now(), now()
FROM subscription_plans p
CROSS JOIN (
    VALUES
        ('broadcast.max_recipients', 500, 'recipients'),
        ('users.max_count', 3, 'users'),
        ('whatsapp.max_accounts', 1, 'accounts'),
        ('sms.max_accounts', 1, 'accounts'),
        ('email.max_accounts', 1, 'accounts'),
        ('ads.max_providers', 1, 'providers'),
        ('whatsapp.templates.max_count', 1, 'templates'),
        ('email.templates.max_count', 1, 'templates'),
        ('email.daily_free_limit', 500, 'segments')
) AS limits(feature_key, limit_value, unit)
WHERE p.code = 'FREE_ORGANIZATION'
ON CONFLICT (plan_id, feature_key) DO NOTHING;

INSERT INTO subscription_plan_limits(plan_id, feature_key, limit_value, unit, created_at, updated_at)
SELECT p.id, limits.feature_key, limits.limit_value, limits.unit, now(), now()
FROM subscription_plans p
CROSS JOIN (
    VALUES
        ('broadcast.max_recipients', 500, 'recipients'),
        ('whatsapp.max_accounts', 1, 'accounts'),
        ('sms.max_accounts', 1, 'accounts'),
        ('email.max_accounts', 1, 'accounts'),
        ('ads.max_providers', 1, 'providers'),
        ('whatsapp.templates.max_count', 1, 'templates'),
        ('email.templates.max_count', 1, 'templates'),
        ('email.daily_free_limit', 500, 'segments')
) AS limits(feature_key, limit_value, unit)
WHERE p.code = 'FREE_INDIVIDUAL'
ON CONFLICT (plan_id, feature_key) DO NOTHING;

INSERT INTO subscription_channel_pricing(
    plan_id, channel, message_type, price_per_segment, free_daily_segments, currency, active, created_at, updated_at)
SELECT p.id, pricing.channel, pricing.message_type, pricing.price_per_segment, pricing.free_daily_segments, 'INR', true, now(), now()
FROM subscription_plans p
CROSS JOIN (
    VALUES
        ('EMAIL', 'PROMOTIONAL', 0.2000, 500),
        ('EMAIL', 'CONVERSATIONAL', 0.2000, 500),
        ('WHATSAPP', 'PROMOTIONAL', 0.9000, 0),
        ('WHATSAPP', 'CONVERSATIONAL', 0.9000, 0),
        ('SMS', 'PROMOTIONAL', 0.0000, 0),
        ('SMS', 'CONVERSATIONAL', 0.0000, 0)
) AS pricing(channel, message_type, price_per_segment, free_daily_segments)
WHERE p.code IN ('FREE_INDIVIDUAL', 'FREE_ORGANIZATION')
ON CONFLICT (plan_id, channel, message_type) DO NOTHING;
